### ISSUE TITLE
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

### ISSUE THREAD

**Issue by beaudevanney** [titaniumnetwork-dev/Ultraviolet-Node-Archive#11]
In Heroku

**Comment by DakshG07** [comment]
Same thing happened for me, currently just working off a fork I made: https://github.com/DakshG07/ultraviolet-node

**Comment by walkthestars** [comment]
Have you fixed your issue yet? I have a way to fix this if you have not.

**Comment by shirt-dev** [comment]
No support will be given for Heroku as they are actively blocking this repo.
