### ISSUE TITLE
400 Bad Request - cloudflare

### ISSUE THREAD

**Issue by Quart2629** [titaniumnetwork-dev/Ultraviolet-Node-Archive#12]
When I deploy on repl, it says this when I try to use it.

![image](https://user-images.githubusercontent.com/60115192/157355209-a5a8a922-309d-4cc6-90c8-18c3c1861881.jpeg)

**Comment by DakshG07** [comment]
You probably want to update, I'm pretty sure they changed something involving that `tomphttp` library. (So, maybe reclone the repository)

**Comment by nightwalnut** [comment]
i did it still doesnt work

**Comment by onlycs** [comment]
+1 fix. this is on discord for me

**Comment by caracal-js** [comment]
Update UV
