### ISSUE TITLE
heroku app not workin

### ISSUE THREAD

**Issue by sillyangel** [titaniumnetwork-dev/Ultraviolet-Node-Archive#15]
its just a blank page

**Comment by ghost** [comment]
I have the same problem. After forking this repository, I linked it with github and deployed it on heroku. I want you to fix it as soon as possible.

**Comment by sillyangel** [comment]
wydm? i did

**Comment by shirt-dev** [comment]
Duplicate of #11.

No support will be given for Heroku as they are actively blocking this repo.
