### ISSUE TITLE
What should i do

### ISSUE THREAD

**Issue by Thewierduser** [titaniumnetwork-dev/Ultraviolet-Node-Archive#28]
It's an issue with compatibility I tried it several times same results. Not sure how to fix it. image has console info for the error.
![Screenshot 2022-03-27 144102](https://user-images.githubusercontent.com/93506660/160302219-91725d7b-cd9f-4d24-b051-9c7358f5b6f0.png)

**Comment by Rockpods** [comment]
Run the following commands in the console first:

```sh
git submodule --init --recursive
npm install
```

Then run npm start

**Comment by caracal-js** [comment]
Follow the above
