### ISSUE TITLE
replit short term loss

### ISSUE THREAD

**Issue by MasterKitten-lab** [titaniumnetwork-dev/Ultraviolet-Node-Archive#29]
Every time I do the quick deploy to replit it works, but if I turn my laptop off for a few hours or something and it disconnects, then once I turn it back on, the repl doesn't run and you would assume you could just stop it and re run it again but no, the repl decides that once you try to run it again that it doesn't want to agree and I have to delete my repl that I made and make a new one with the same name, otherwise my browser history is lost and I have to relog my accounts.

**Comment by shirt-dev** [comment]
Do not open issues for repl.it, it is not supported.
