### ISSUE TITLE
Github Pages

### ISSUE THREAD

**Issue by EmulatorOS** [titaniumnetwork-dev/Ultraviolet-Node-Archive#32]
Is there a way to run this on github pages?

**Comment by YodaLightsabr** [comment]
> Is there a way to run this on github pages?

@EmulatorOS No, because it requires server control. GitHub Pages can only serve frontend content.

**Comment by EmulatorOS** [comment]
What about cloudflare?

**Comment by jackchristel** [comment]
No you need something that can run a nodejs application.

**Comment by EmulatorOS** [comment]
What about cloudflare?

**Comment by EmulatorOS** [comment]
I dont know much about these

**Comment by jackchristel** [comment]
You need to use replit or something similar (I am not liable if you get banned from replit as they don't allow proxies I'm pretty sure).

**Comment by EmulatorOS** [comment]
Thats the reason that im not using them. Is there any alternatives that are good?

**Comment by jackchristel** [comment]
You might be able to use Netlify possibly, there aren't many free alternatives that I know of.
