### ISSUE TITLE
the xml file does not appear to have any style information associated with it

### ISSUE THREAD

**Issue by av0idchase** [titaniumnetwork-dev/Ultraviolet-Node-Archive#37]
Everytime I try to log in to GeForce now if get the error

the xml file does not appear to have any style information associated with it

<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>DXW3AC1TF4PNX79C</RequestId>
<HostId>(HostID)</HostId>
</Error>

**Comment by shirt-dev** [comment]
This is not an issue with the proxy
