### ISSUE TITLE
Problem using Ultraviolet on some ARM based browsers 

### ISSUE THREAD

**Issue by hodss** [titaniumnetwork-dev/Ultraviolet-Node-Archive#38]
## Expected Behavior
When attempting to go to a website with the bar with the text "Search the web freely" you should be able to press the enter key and go to associated website.

## Current Behavior
Attempting to do so fails, and will give you a Page Not Found error or just completely fail to function.

## Possible Solution
A solution should be to simply add a button that when used by a mouse will function like the enter key, which is simple, but some may not know how to do this, and may not understand.

## Steps to Reproduce
1. any ultraviolet node will do, mine being https://deweyy.gq
2. open said link, or any other 
3. attempt in the web address bar to type any web address. Me, attempting my own website and https://www.google.com
4. the input form seems to not recognize said input and should not respond

## Context (Environment)
PC that was used:
Raspberry Pi 400 OC to 2.2 GHz (if relevant)
OS: Raspbian (Raspberry Pi OS) 32 Bit, slightly modified kernel to allow turbo
Browser: Chromium 78.0.3904.108 Raspbian 10 (32-bit)
JavaScript Version: V8 7.8.279.23

## Additional information
I have ensured that this is not a keyboard issue.

**Comment by shirt-dev** [comment]
Does the issue occur on latest Chromium?

**Comment by hodss** [comment]
@shirt-dev Sorry for a late response.

(I'm unsure if you have permission to accept pull requests so some of the things at the conclusion section may not be possible)

## Does the issue occur on latest Chromium update?
**After updating Chromium and updating the firmware and drivers of my Pi I was able to get it functional**

Chromium browsers do not auto-update so sorry about this 

However:

## Problems faced on other browsers
**I am still facing this problem on the Tor browser on the same device.**
Additionally after disconnecting from the Tor network and attempting to use my Node, it still failed to function as intended.

## Conclusion

An addition of a warning to update your browser if you're running Chromium would be useful. Additionally, a warning about not using the Tor browser on ARM with certain 32-bit systems until someone figures out how to make it function properly would be useful as well. Maybe documentation about adding a button to launch the service, however that is probably much more complicated than just adding a form submission button.

### If anyone is curious about the proper terminal commands and steps to update chromium on Raspbian and Debian here they are:

1. do Crtl + Alt + T
2. Run `sudo apt-get update`
3. If it asks for a confirmation prompt, type `y`
4. Run `sudo apt-get install chromium-browser`
5. If it asks for a confirmation prompt, type `y`

You may still receive update prompts in-browser, but they are false.

To update firmware:
(Got lazy and stopped writing, updating firmware is more complicated as it involves finding underlying packages to apt-get, if you need to update your firmware, leave a post here or dm me on twitter, or email me, probably best to email.)

Best regards

**Comment by shirt-dev** [comment]
Ultraviolet appears to be working on the latest releases of Chromium and Firefox, which are what we are targeting with this project. Chrome and Firefox have their own updater on most platforms.

I do know that this project uses some newer JavaScript features, which could play a factor here.

I would assume that Tor Browser isn't really a priority for the project since the entire purpose of Ultraviolet is to proxy webpages to circumvent network restrictions, something that Tor Browser already achieves on its own.

I am closing this issue as I consider this not to be an issue with Ultraviolet itself.
