### ISSUE TITLE
"TypeError: Failed to fetch" repl deploy

### ISSUE THREAD

**Issue by Quart2629** [titaniumnetwork-dev/Ultraviolet-Node-Archive#4]

**Comment by s191ed** [comment]
have you ran git submodule update --init on the bash command?
this should solve the issue because mine is working

**Comment by s191ed** [comment]
edit: nevermind

**Comment by caracal-js** [comment]
Hello, "TypeError: Failed to fetch" is an issue thats been reported multiple times. Can you please tell me your browser, and web filter?

**Comment by BEASTMODE2629** [comment]
Chrome, content keeper

**Comment by Quart2629** [comment]
Chrome, content keeper

**Comment by shirt-dev** [comment]
Repl is not supported
