### ISSUE TITLE
Skip Ad button on YouTube gone

### ISSUE THREAD

**Issue by bleov** [titaniumnetwork-dev/Ultraviolet-Node-Archive#47]
i think that this counts as a "blocked site issue" or something but I don't care either.
Youtube's not even blocked I just through you should know

the skip ad button is gone (oh no)
## Expected Behavior

it should be there 🤯

## Current Behavior

it's not there 🤯🤯😮 

## Possible Solution

dont have one sorry

## Steps to Reproduce

1. go to youtube (i've tried it on replit and self hosted and the both have the same issue)
2. click a video
3. done

## Context (Environment)

How has this issue affected me???

grammarly and 40 minute ads about diet

## Detailed Description

im good

## an artist's rendition of the issue
![Screenshot 2022-06-05 8 03 21 AM](https://user-images.githubusercontent.com/48164825/172049585-067105c3-b1f1-4f14-a78e-d16433349eff.png)

## an ai's rendition of me after watching a 50 second grammarly ad
![image](https://user-images.githubusercontent.com/48164825/172050014-5f4f4e8a-c4bf-44f7-a77b-59418567cb6a.png)

**Comment by caracal-js** [comment]
This problem occurs due to ad-blockers deleting the button based on an HTML property of it (class, attribute, text).
